image: ubuntu:xenial

before_script:
  - apt update && apt upgrade && apt install psmisc
  - fuser -i 3000/tcp
  - fuser -k 3000/udp
  - apt update && apt upgrade

stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - docker
  script:
    - apt install curl
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - npm install
    - npm build

deploy:
  stage: deploy
  only:
    - master
  tags: 
    - ssh
  script: 
    - npm install
    - forever start app.js
