image: ubuntu:xenial

before_script:
  - apt update && apt upgrade -y
  - apt install -y curl openssh-client
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt install -y nodejs
  - npm install

stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - docker
  script:
    - npm build

deploy:
  stage: deploy
  only:
    - master
  tags: 
    - docker
  script:
    - ssh root@vps.noeldupuis.fr /var/DMXController/script.sh
